Repository ProjectEvergreen/www.greenwoodjs.dev, pull requests merged in 2024-09, with the labels that each got.

#84 feature/issue 34 blog landing page and all posts
  greenwood.config.js
  package-lock.json
  package.json
  patches/@greenwood+cli+0.30.0-alpha.5.patch
  src/assets/blog/dev-cache-step1.png
  src/assets/blog/dev-cache-step2.png
  src/assets/blog/dev-cache-step3.png
  src/assets/blog/dev-cache-step4.png
  src/assets/blog/evergreen.svg
  src/assets/blog/full-stack-web-components.webp
  src/assets/blog/greenwood-logo-1000w.webp
  src/assets/blog/greenwood-logo-1500w.webp
  src/assets/blog/greenwood-logo-300w.webp
  src/assets/blog/greenwood-logo-500w.webp
  src/assets/blog/greenwood-logo-750w.webp
  src/assets/blog/greenwood-starter-presentation.png
  src/assets/blog/hud.png
  src/assets/blog/init-scaffolding.png
  src/assets/blog/nodejs.png
  src/assets/blog/not-found.png
  src/assets/blog/serverless.webp
  src/assets/blog/ssr.webp
  src/assets/blog/wcc-logo.png
  src/assets/greenwood-logo-full.svg
  src/assets/greenwood-logo-g.svg
  src/assets/greenwood-logo-leaf.svg
  src/assets/link.svg
  src/components/blog-posts-list/blog-posts-list.js
  src/components/blog-posts-list/blog-posts-list.module.css
  src/layouts/app.html
  src/layouts/blog.html
  src/pages/blog/index.html
  src/pages/blog/release/v0-15-0.md
  src/pages/blog/release/v0-18-0.md
  src/pages/blog/release/v0-19-0.md
  src/pages/blog/release/v0-20-0.md
  src/pages/blog/release/v0-21-0.md
  src/pages/blog/release/v0-23-0.md
  src/pages/blog/release/v0-24-0.md
  src/pages/blog/release/v0-26-0.md
  src/pages/blog/release/v0-27-0.md
  src/pages/blog/release/v0-28-0.md
  src/pages/blog/release/v0-29-0.md
  src/pages/blog/state-of-greenwood-2022.md
  src/pages/blog/state-of-greenwood-2023.md
  src/pages/index.md
  src/stories/Styleguide.mdx
  src/styles/blog.css
  src/styles/theme.css
Labels: enhancement, question, needs upstream, content:copy

#87 chore/upgrade greenwood v0.30.0-alpha.6
  .nvmrc
  CONTRIBUTING.md
  greenwood.config.js
  package-lock.json
  package.json
  patches/@greenwood+cli+0.30.0-alpha.5.patch
  patches/@greenwood+cli+0.30.0-alpha.6.patch
  src/components/capabilities/capabilities.js
  src/components/copy-to-clipboard/copy-to-clipboard.js
Labels: enhancement, chore

#86 enhancement/issue 71 acquire svgs for all assets
  src/assets/github.svg
  src/assets/netlify.png
  src/assets/netlify.svg
  src/assets/node.png
  src/assets/nodejs.svg
  src/assets/vercel.svg
  src/assets/wcc.svg
  src/components/run-anywhere/platforms.json
  src/components/run-anywhere/run-anywhere.js
  src/components/run-anywhere/run-anywhere.module.css
Labels: enhancement

#85 enhancement/issue 30 apply bold font family to key home page headings
  src/components/build-with-friends/build-with-friends.module.css
  src/components/capabilities/capabilities.css
  src/components/get-started/get-started.module.css
  src/components/header/header.module.css
  src/components/hero-banner/hero-banner.module.css
  src/components/run-anywhere/run-anywhere.module.css
  src/components/why-greenwood/why-greenwood.module.css
  src/styles/home.css
Labels: enhancement

#93 content/promote usage of init with project name flag
  src/components/get-started/get-started.js
  src/components/get-started/get-started.module.css
  src/components/hero-banner/hero-banner.js
  src/components/hero-banner/hero-banner.module.css
Labels: content
