Repository ProjectEvergreen/www.greenwoodjs.dev, pull requests merged in 2024-10, with the labels that each got.

#101 enhancement/home page content formatting and banner responsiveness
  src/components/get-started/get-started.js
  src/components/get-started/get-started.module.css
  src/components/hero-banner/hero-banner.js
  src/components/hero-banner/hero-banner.module.css
  src/components/latest-post/latest-post.js
  src/components/latest-post/latest-post.module.css
  src/pages/index.md
  src/styles/home.css
Labels: enhancement

#100 enhancement/display published date for blog posts list
  src/components/blog-posts-list/blog-posts-list.js
  src/components/blog-posts-list/blog-posts-list.module.css
  src/components/blog-posts-list/blog-posts-list.spec.js
Labels: enhancement

#102 chore/issue 43 linting for markdown and JSON
  CONTRIBUTING.md
  eslint.config.js
  package-lock.json
  package.json
  src/components/blog-posts-list/blog-posts-list.spec.js
  src/pages/blog/release/v0-19-0.md
  src/pages/blog/release/v0-28-0.md
  src/pages/blog/state-of-greenwood-2023.md
  src/pages/guides/ecosystem/storybook.md
  src/pages/guides/ecosystem/web-test-runner.md
  src/pages/guides/tutorials/theme-packs.md
Labels: content, chore

#108 Issue-79: Recreate the json.svg to better align
  src/assets/json.svg
  src/components/capabilities/capabilities.js
  src/components/capabilities/capabilities.stories.js
  src/pages/index.md
Labels: enhancement

#106 bug/capabilities mobile style fixes
  src/assets/api-routes.svg
  src/components/capabilities/capabilities.css
  src/components/capabilities/capabilities.js
  src/components/header/header.module.css
Labels: bug

#109 enhancement/Issue-99: Refactor keyframes to be a transition
  src/components/side-nav/side-nav.module.css
  src/components/table-of-contents/table-of-contents.module.css
Labels: enhancement, hacktoberfest-accepted

#111 feature/Issue-97: Implement the Edit on GitHub component
  src/components/edit-on-github/edit-on-github.js
  src/components/edit-on-github/edit-on-github.module.css
  src/components/edit-on-github/edit-on-github.spec.js
  src/components/edit-on-github/edit-on-github.stories.js
  src/layouts/guides.html
  src/stories/mocks/graph.json
Labels: enhancement, hacktoberfest-accepted

#113 bug/Issue-91: Refactor headers styles to prevent logo from shrinking
  src/components/header/header.module.css
Labels: bug, hacktoberfest-accepted

#112 chore/Issue-51: Refactor lint-staged config
  lint-staged.config.js
  package-lock.json
  package.json
  src/components/capabilities/capabilities.css
  src/components/copy-to-clipboard/copy-to-clipboard.css
  src/components/footer/footer.module.css
  src/components/header/header.module.css
  src/components/hero-banner/hero-banner.module.css
  src/components/side-nav/side-nav.module.css
  stylelint.config.js
Labels: chore, hacktoberfest-accepted

#115 Issue-110: Additional testing details: reference/link existing wtr docs
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, documentation

#116 bug/issue 30 restore click target to home page npx CTA
  src/components/hero-banner/hero-banner.module.css
Labels: bug

#121 chore/Issue-119: Setup project with Stylelint a11y plugin
  package-lock.json
  package.json
  src/components/blog-posts-list/blog-posts-list.module.css
  src/components/capabilities/capabilities.css
  src/components/get-started/get-started.module.css
  src/components/header/header.module.css
  src/components/hero-banner/hero-banner.module.css
  src/components/run-anywhere/run-anywhere.module.css
  src/components/side-nav/side-nav.module.css
  src/components/table-of-contents/table-of-contents.module.css
  src/styles/theme.css
  stylelint.config.js
Labels: enhancement, chore, hacktoberfest-accepted

#107 chore/upgrade greenwood v0.30.0 alpha.7
  CONTRIBUTING.md
  eslint.config.js
  greenwood.config.js
  package-lock.json
  package.json
  patches/@greenwood+cli+0.30.0-alpha.6.patch
  patches/wc-compiler+0.14.0.patch
  plugin-css-modules.js
  src/components/blog-posts-list/blog-posts-list.js
  src/components/blog-posts-list/blog-posts-list.stories.js
  src/components/capabilities/capabilities.js
  src/components/copy-to-clipboard/copy-to-clipboard.js
  src/components/side-nav/side-nav.js
  src/components/side-nav/side-nav.spec.js
  src/components/side-nav/side-nav.stories.js
  src/components/table-of-contents/table-of-contents.js
  src/components/table-of-contents/table-of-contents.stories.js
  src/pages/guides/ecosystem/storybook.md
  src/pages/guides/ecosystem/web-test-runner.md
Labels: docs, chore, documentation

#122 enhancement/issue 88 header navigation using content as data
  src/components/header/header.js
  src/components/header/header.module.css
  src/components/header/header.spec.js
  src/components/header/header.stories.js
  src/layouts/app.html
  src/pages/blog/index.html
  src/pages/docs/index.md
  src/pages/guides/index.md
  src/stories/mocks/graph.json
Labels: enhancement
