Repository ProjectEvergreen/www.greenwoodjs.dev, pull requests merged in 2024-05, with the labels that each got.

#41 docs/issue 39 contributing guidelines
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  src/stories/Documentation.mdx
  src/stories/Techstack.mdx
Labels: documentation

#38 enhancement/issue 7 open props
  .storybook/preview.js
  package-lock.json
  package.json
  patches/@greenwood+cli+0.29.0.patch
  src/pages/index.html
  src/stories/Styleguide.mdx
  src/stories/Techstack.mdx
  src/styles/main.css
  src/styles/theme.css
Labels: documentation, enhancement, needs upstream

#40 chore/issue 24 formatting and linting
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .husky/.gitignore
  .husky/pre-commit
  .ls-lint.yml
  .nvmrc
  .prettierrc
  .storybook/main.js
  .storybook/preview.js
  CONTRIBUTING.md
  eslint.config.js
  greenwood.config.js
  package-lock.json
  package.json
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
  src/components/footer/footer.stories.js
  src/pages/index.html
  src/stories/Configure.mdx
  src/stories/Documentation.mdx
  src/stories/Styleguide.mdx
  src/stories/Techstack.mdx
  src/styles/main.css
  src/styles/theme.css
  stylelint.config.js
  web-test-runner.config.js
Labels: question, chore

#45 chore/upgrade greenwood v0.30.0-alpha.2
  .nvmrc
  netlify.toml
  package-lock.json
  package.json
  patches/@greenwood+cli+0.29.0.patch
  patches/@greenwood+cli+0.30.0-alpha.2.patch
Labels: chore

#46 chore/bump node engines
  package.json
Labels: chore

#44 feature/issue 26 header component
  .storybook/main.js
  eslint.config.js
  greenwood.config.js
  package-lock.json
  package.json
  patches/wc-compiler+0.13.0.patch
  src/assets/tile.svg
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/header.spec.js
  src/components/header/header.stories.js
  src/styles/theme.css
  vite.config.js
  web-test-runner.config.js
Labels: documentation, enhancement, help wanted

#11 CSS Modules
  .ls-lint.yml
  .storybook/main.js
  greenwood.config.js
  package-lock.json
  package.json
  patches/@greenwood+cli+0.30.0-alpha.2.patch
  plugin-css-modules.js
  src/components/footer/footer.js
  src/components/footer/footer.module.css
  src/styles/main.css
  vite.config.js
  web-test-runner.config.js
Labels: documentation, enhancement, needs upstream, demo
