Repository ProjectEvergreen/www.greenwoodjs.dev, pull requests merged in 2024-07, with the labels that each got.

#69 Enhancement/Issue 68 add anchor link to header logo
  src/components/header/header.js
  src/components/header/header.spec.js
Labels: enhancement

#67 bug/issue 66 vertically center align Twitter / X social icons
  src/components/footer/footer.module.css
  src/components/header/header.css
Labels: bug

#61 bug/issue 59 apply semantic HTML to header social links list
  src/components/header/header.js
  src/components/header/header.spec.js
Labels: bug

#64 bug/issue 47 updated greenwood logo
  plugin-css-modules.js
  src/assets/greenwood-logo-full.svg
  src/assets/greenwood-logo-g.svg
  src/assets/greenwood-logo-leaf.svg
  src/assets/greenwood-logo.svg
  src/components/footer/footer.js
  src/components/footer/footer.module.css
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/header.spec.js
  src/stories/Styleguide.mdx
  src/styles/theme.css
  src/templates/app.html
Labels: bug, documentation, enhancement

#65 chore/upgrade greenwood v0.30.0-alpha.4
  package-lock.json
  package.json
  patches/@greenwood+cli+0.30.0-alpha.2.patch
  patches/wc-compiler+0.14.0.patch
  src/layouts/app.html
Labels: chore
